# Generated by Django 3.0.8 on 2020-08-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.TextField(blank=True, default='')),
                ('item_media_array', models.TextField(blank=True, default='')),
                ('item_name', models.TextField(blank=True, default='')),
                ('dev_term', models.TextField(blank=True, default='')),
                ('dev_intro', models.TextField(blank=True, default='')),
                ('dev_feature', models.TextField(blank=True, default='')),
                ('dev_review', models.TextField(blank=True, default='')),
            ],
        ),
    ]
