# Generated by Django 3.0.8 on 2020-07-12 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('naver', models.TextField(blank=True, default='')),
                ('zdnet', models.TextField(blank=True, default='')),
                ('sbs', models.TextField(blank=True, default='')),
                ('kbs', models.TextField(blank=True, default='')),
                ('jtbc', models.TextField(blank=True, default='')),
                ('tech', models.TextField(blank=True, default='')),
                ('etc', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.DeleteModel(
            name='EtcData',
        ),
        migrations.DeleteModel(
            name='JtbcData',
        ),
        migrations.DeleteModel(
            name='KbsData',
        ),
        migrations.DeleteModel(
            name='NaverData',
        ),
        migrations.DeleteModel(
            name='SbsData',
        ),
        migrations.DeleteModel(
            name='TechCrunchData',
        ),
        migrations.DeleteModel(
            name='ZdnetData',
        ),
    ]
